name: PR CI (tests only)

on:
  pull_request:
    branches: [ dev ]

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: pr-ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Gradle Wrapper Validate
        uses: gradle/actions/wrapper-validation@v3
        continue-on-error: true
        timeout-minutes: 5

      - name: Run preflight (tests + coverage)
        env:
          CI: "true"
        run: ./gradlew --no-daemon clean preflight "-Dorg.gradle.jvmargs=-Xmx2g"
